name: Telegram Daily Quiz

on:
  workflow_dispatch:
  schedule:
    - cron: '30 9 * * *'

jobs:
  quiz:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python bot.py
# test
